From ubuntu:16.04

#暴露22端口
EXPOSE	22

#安装ssh
RUN 	apt-get update \
	&& apt-get install -y openssh-server curl git subversion ctags locales net-tools \
	&& apt-get install -y gcc g++ clang python python3 make build-essential cmake python3-dev python-dev \
	&& apt-get install -y software-properties-common \
	&& add-apt-repository ppa:jonathonf/vim -y && apt-get update &&  apt-get install -y vim \
	&& apt-get autoremove \
	&& mkdir -p /var/run/sshd \
	&& sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config \
	&& echo 'root:@^#EMA' |chpasswd 

#系统时间
WORKDIR /root/
ENV 	TZ=Asia/Shanghai
RUN 	ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

#安装vim
ADD	./vim-config/.vimrc 	/root/.vimrc
ADD	./vim-config/.vim	/root/.vim
RUN	mkdir -p /root/.vim/bundle && cd /root/.vim/bundle && git clone https://github.com/VundleVim/Vundle.vim.git \
	&& git clone https://github.com/Valloric/YouCompleteMe.git && cd YouCompleteMe && git submodule update --init --recursive \
	&& YCM_CORES=1 ./install.py --clang-completer \
	&& rm -f /tmp/* \
	&& vim -c 'PluginInstall' -c 'qa!'

#安装bear
RUN	git https://github.com/rizsotto/Bear.git &&cd Bear && mkdir -p build && cd build && cmake .. && make && make install && cd ../../ && rm -rf Bear &&rm -f /tmp/* \
	&& echo "export LC_ALL=C.UTF-8" >> /etc/profile && echo "export LANG=C.UTF-8" >>/etc/profile

#启动命令
COPY	start.sh /bin/start.sh
ENTRYPOINT	["/bin/start.sh"]

